apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app-ingress
  annotations:
    # We use the "GCE" class (Google Compute Engine standard LB)
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: node-app-service
      port:
        number: 80
