apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: ClusterIP # Internal only. Not reachable from the internet.
  selector:
    app: node-app # Finds pods with this label
  ports:
    - protocol: TCP
      port: 80 # The port the Service listens on (internal DNS)
      targetPort: 3000 # The port your Node.js app is actually running on
