apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  annotations:
    # This creates a "Network Endpoint Group" (NEG).
    # It allows the Load Balancer to talk DIRECTLY to Pod IPs (faster, native GCP performance).
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP # We revert to ClusterIP, but the NEG annotation makes it visible to Ingress
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
